namespace Albedo.Enums
{
    public enum PairMarketType
    {
        None,
        Spot,
        SpotUsdt,
        SpotTusd,
        SpotBusd,
        SpotBnb,
        SpotBtc,
        SpotEth,
        SpotDai,
        SpotUsdc,
        SpotVai,
        SpotXrp,
        SpotTrx,
        SpotDoge,
        SpotDot,
        SpotAud,
        SpotBidr,
        SpotBrl,
        SpotEur,
        SpotGbp,
        SpotRub,
        SpotTry,
        SpotUah,
        SpotZar,
        SpotIdrt,
        SpotNgn,
        SpotPln,
        SpotRon,
        SpotArs,
        Futures,
        CoinFutures
    }
}
